import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font';
import './globals.css'
import MainLayout from "@/components/layouts/MainLayout";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={GeistSans.className}>
      <body>
        <div>
          <MainLayout>
            {children}
          </MainLayout>
        </div>
      </body>
    </html>
  )
}
