import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font';
import './globals.css'
import MainLayout from "@/app/_components/templates/MainLayout";
import AuthSession from "@/app/_components/wrapper/AuthSession";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={GeistSans.className}>
      <body>
        {/*<AuthSession>*/}
          <div>
            <MainLayout>
              {children}
            </MainLayout>
          </div>
        {/*</AuthSession>*/}
      </body>
    </html>
  )
}
