import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font';
import './globals.css'
import MainLayout from "@/app/_components/templates/MainLayout";
import AuthSession from "@/app/_components/wrapper/AuthSession";
import ToastWrapper from "@/app/_components/wrapper/ToastWrapper";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={GeistSans.className}>
    <body>
      <div className="relative">
        <AuthSession>
          <div>
            <MainLayout>
              {children}
            </MainLayout>
          </div>
        </AuthSession>
      </div>
      <div id="toast-root" className="absolute left-0 top-0 w-full">
        <ToastWrapper />
      </div>
    </body>
    </html>
  )
}
